export const proteinShakeRecipe = {
  title: "Incremente seu shake proteico",
  content: "Para preparar sua comida Incremente seu shake proteico, você precisará dos seguintes ingredientes:\n\n- 1 xícara de leite de sua preferência (pode ser leite de amêndoa, leite de coco, leite de soja, etc.)\n- 1 banana madura\n- 1 colher de sopa de manteiga de amendoim ou amêndoas\n- 1 colher de sopa de proteína em pó de sua escolha (pode ser whey protein, proteína vegana, etc.)\n- 1 colher de chá de mel ou adoçante de sua preferência (opcional)\n- 1/2 xícara de gelo\n\nInstruções:\n\n1. Em um liquidificador, adicione o leite, a banana, a manteiga de amendoim e a proteína em pó.\n2. Se desejar um sabor mais doce, adicione o mel ou o adoçante de sua preferência.\n3. Adicione o gelo.\n4. Bata tudo no liquidificador até obter uma mistura homogênea e cremosa.\n5. Se preferir, você pode adicionar algumas frutas frescas, como morangos ou blueberries, para dar um toque extra de sabor e nutrientes.\n6. Sirva seu shake proteico imediatamente e aproveite!\n\nLembrando que você pode ajustar os ingredientes de acordo com suas preferências e necessidades nutricionais."
}

export const quinoaSaladRecipe = {
  title: "Salada de Quinoa com Legumes",
  content: "A seguir está uma receita básica de Salada de Quinoa com Legumes:\n\nIngredientes:\n- 1 xícara de quinoa\n- 2 xícaras de água\n- 1 pimentão vermelho, cortado em cubos\n- 1 pepino, cortado em cubos\n- 1 cenoura, ralada\n- 1 abobrinha, cortada em cubos\n- 1 cebola roxa, fatiada\n- 1/2 xícara de salsinha picada\n- 1/4 xícara de azeite de oliva\n- Suco de 1 limão\n- Sal e pimenta a gosto\n\nInstruções:\n\n1. Lave bem a quinoa em água corrente para remover a saponina, uma substância natural que pode deixar um sabor amargo. Escoe bem.\n\n2. Em uma panela, adicione a quinoa e a água. Leve ao fogo alto até ferver. Reduza o fogo para médio-baixo, tampe e cozinhe por cerca de 15 minutos, ou até que a quinoa esteja macia e toda a água tenha sido absorvida. Retire do fogo e deixe esfriar.\n\n3. Enquanto a quinoa cozinha, prepare os legumes. Corte o pimentão, o pepino, a cenoura, a abobrinha e a cebola como indicado nas medidas acima.\n\n4. Em uma tigela grande, misture os legumes cortados, a quinoa cozida e a salsinha picada.\n\n5. Em uma tigela separada, prepare o molho da salada, misturando o azeite de oliva, o suco de limão, o sal e a pimenta.\n\n6. Despeje o molho sobre a salada de quinoa e legumes e misture bem para que todos os ingredientes se incorporem.\n\n7. Sirva imediatamente ou leve à geladeira por pelo menos 1 hora para resfriar antes de servir.\n\nEssa é uma receita básica, mas você pode adicionar outros legumes e temperos de sua preferência para personalizar a salada."
}

export const chickenWithPotatoAndAspargusRecipe = {
  title: "Frango Grelhado com Batata Doce e Aspargos",
  content: "Aqui está uma possível forma de preparar essa refeição:\n\nIngredientes:\n- 2 peitos de frango\n- Sal e pimenta a gosto\n- 2 colheres de sopa de azeite\n- 2 batatas doces médias\n- 1 maço de aspargos\n- Temperos a gosto (alho em pó, paprika, cominho, etc.)\n\nInstruções:\n\n1. Pré-aqueça o forno a 200°C.\n2. Tempere os peitos de frango com sal e pimenta a gosto.\n3. Aqueça o azeite em uma frigideira em fogo médio-alto e doure os peitos de frango por cerca de 4-5 minutos de cada lado, até que fiquem bem dourados. Transfira os peitos de frango para uma assadeira.\n4. Enquanto isso, lave e corte as batatas doces em rodelas grossas.\n5. Coloque as rodelas de batata doce em uma tigela e regue com um pouco de azeite. Tempere com sal, pimenta e outros temperos de sua escolha, como alho em pó, paprika, cominho, etc. Misture bem para cobrir uniformemente as batatas doces.\n6. Adicione as batatas doces temperadas à assadeira ao redor dos peitos de frango.\n7. Lave os aspargos, corte a extremidade mais dura e coloque-os na assadeira ao lado do frango e das batatas doces.\n8. Tempere os aspargos com azeite e temperos de sua escolha.\n9. Asse tudo no forno por cerca de 20-25 minutos, ou até que o frango esteja totalmente cozido e as batatas doces estejam macias e douradas.\n10. Retire do forno e sirva imediatamente.\n\nEssa é apenas uma sugestão de preparo, e você pode ajustar os temperos de acordo com suas preferências. Bom apetite!",
}

export const omeletWithCheeseRecipe = {
  title: "Omelete de Espinafre e Queijo Cottage",
  content: "Para preparar o omelete de espinafre e queijo cottage, siga os seguintes passos:\n\n1. Em uma tigela, bata 3 ovos até ficarem bem misturados.\n2. Adicione uma pitada de sal e pimenta a gosto.\n3. Em uma frigideira antiaderente, aqueça um pouco de azeite em fogo médio.\n4. Adicione uma xícara de espinafre picado à frigideira e cozinhe por cerca de 2 minutos, até que o espinafre murche.\n5. Despeje os ovos batidos sobre o espinafre na frigideira.\n6. Com uma espátula, mexa suavemente os ovos enquanto cozinham, para que cozinhem de maneira uniforme.\n7. Quando o omelete estiver quase pronto, adicione 1/4 de xícara de queijo cottage por cima.\n8. Dobre o omelete ao meio, cobrindo o queijo cottage, e cozinhe por mais 1 a 2 minutos até que o queijo derreta.\n9. Retire da frigideira e sirva o omelete quente.\n\nVocê também pode adicionar outros ingredientes de sua preferência, como tomate picado, cogumelos ou cebola, para tornar o omelete mais saboroso.",
}

export const salmonWithQuinoaAndVegetablesRecipe = {
  title: "Salmão Assado com Quinoa e Legumes no Vapor",
  content: "Aqui está uma receita básica para o preparo do \"Salmão Assado com Quinoa e Legumes no Vapor\":\n\nIngredientes:\n- 2 filés de salmão\n- 1 xícara de quinoa\n- 2 xícaras de água\n- Legumes de sua preferência (como brócolis, cenoura, ervilhas, etc.)\n- Sal e pimenta a gosto\n- Azeite de oliva\n- Limão (opcional)\n- Ervas frescas para temperar (como salsa, coentro, endro ou manjericão)\n\nInstruções:\n\n1. Pré-aqueça o forno a 200ºC.\n\n2. Cozinhe a quinoa: Lave a quinoa em água corrente para remover qualquer resíduo amargo e, em seguida, cozinhe-a em uma panela com as duas xícaras de água. Deixe ferver, reduza o fogo para médio/baixo e cozinhe por cerca de 15-20 minutos ou até a quinoa ficar macia e a água tiver sido absorvida. Reserve.\n\n3. Prepare os legumes: Corte os legumes selecionados em pedaços pequenos e uniformes. Reserve.\n\n4. Tempere os filés de salmão: Tempere os filés de salmão com sal, pimenta e o suco de limão (opcional). Se preferir, pode adicionar algumas ervas frescas picadas.\n\n5. Asse o salmão: Em uma assadeira forrada com papel alumínio ou com um pouco de azeite para evitar que o salmão grude, coloque os filés de salmão e leve ao forno pré-aquecido. Asse por aproximadamente 15-20 minutos ou até que o salmão esteja cozido, mas ainda úmido por dentro.\n\n6. Prepare os legumes no vapor: Enquanto o salmão está assando, coloque uma panela com água para ferver. Quando a água estiver fervendo, coloque os legumes em um cesto para cozinhar a vapor e posicione-o sobre a panela. Cozinhe os legumes no vapor por cerca de 5-7 minutos, até que fiquem macios, mas ainda crocantes. Tempere com sal e pimenta a gosto.\n\n7. Montagem: Em cada prato, coloque uma porção de quinoa cozida, um filé de salmão assado e os legumes no vapor ao lado. Regue com um fio de azeite de oliva e decore com ervas frescas picadas.\n\n8. Sirva imediatamente e aproveite!\n\nLembre-se de que esta é apenas uma sugestão básica de receita. Sinta-se à vontade para ajustar os ingredientes e temperos de acordo com suas preferências.",
}

export const smoothieDetoxRecipe = {
  title: "Smoothie Verde Detox",
  content: "Para preparar um Smoothie Verde Detox, você precisará dos seguintes ingredientes:\n\n- 1 xícara de espinafre fresco\n- 1 banana média madura\n- 1 maçã verde\n- 1/2 pepino\n- 1/2 suco de limão\n- 1 copo de água de coco ou água comum\n- Adoçante a gosto (opcional)\n\nAgora, siga as etapas abaixo para preparar o Smoothie Verde Detox:\n\n1. Lave bem o espinafre, a maçã verde e o pepino.\n2. Descasque a banana e a maçã verde.\n3. Corte a banana, a maça verde e o pepino em pedaços pequenos, facilitando a mistura no liquidificador.\n4. Adicione todos os ingredientes, incluindo o espinafre, à jarra do liquidificador.\n5. Esprema o suco de meio limão dentro da jarra.\n6. Adicione o copo de água de coco ou água comum.\n7. Caso goste de um sabor mais doce, adicione um pouco de adoçante (como mel ou estévia) a gosto.\n8. Feche a tampa do liquidificador e misture todos os ingredientes até obter uma consistência suave e sem pedaços.\n9. Se preferir uma consistência mais líquida, adicione mais água de coco ou água.\n10. Prove o smoothie e ajuste os ingredientes de acordo com o seu gosto pessoal.\n11. Sirva o Smoothie Verde Detox em um copo grande ou em potes menores para compartilhar.\n12. Se quiser, decore com um pedaço de maçã verde ou folhas de hortelã.\n13. Consuma imediatamente para aproveitar ao máximo os benefícios dos ingredientes frescos.\n\nAproveite o Smoothie Verde Detox como uma opção saudável e refrescante para começar o dia, ou como um lanche nutritivo ao longo do dia!",
}

export const salmonPokeRecipe = {
  title: "Poke Bowl de Salmão",
  content: "O Poke Bowl de salmão é uma tigela de comida havaiana simples e saudável que geralmente consiste em uma base de arroz de sushi ou quinoa, cubos de salmão fresco marinados, legumes frescos, molho de soja e uma variedade de outros ingredientes saborosos. \n\nAqui está uma receita básica para preparar um Poke Bowl de Salmão:\n\nIngredientes:\n\n- 200 gramas de salmão fresco, cortado em cubos\n- 2 colheres de sopa de molho de soja\n- 1 colher de sopa de óleo de gergelim torrado\n- 1 colher de chá de gengibre ralado\n- 1 colher de chá de mel\n- 2 xícaras de arroz de sushi cozido (ou quinoa)\n- 1 xícara de pepino em cubos\n- 1 xícara de abacate em cubos\n- 1 xícara de cenoura ralada\n- Cebolinha a gosto, picada\n\nModo de preparo:\n\n1. Em uma tigela, combine o salmão cortado em cubos, o molho de soja, o óleo de gergelim torrado, o gengibre ralado e o mel. Misture bem para que o salmão fique marinado nesta mistura por cerca de 15 minutos.\n\n2. Enquanto o salmão está marinando, prepare os outros ingredientes. Cozinhe o arroz de sushi conforme as instruções da embalagem ou cozinhe a quinoa conforme o desejado. Corte o pepino, o abacate e a cenoura em cubos ou fatias finas.\n\n3. Montagem do Poke Bowl: Em uma tigela, coloque uma porção de arroz de sushi (ou quinoa) no fundo. Em seguida, adicione o salmão marinado, o pepino, o abacate e a cenoura ralada. Decore com cebolinha picada por cima.\n\n4. Finalize regando o Poke Bowl com um pouco mais de molho de soja e óleo de gergelim torrado, se desejar. Você também pode adicionar outros ingredientes opcionais, como alga nori em tiras, sementes de gergelim ou molho picante, de acordo com o seu gosto.\n\n5. Sirva imediatamente e aproveite o seu Poke Bowl de Salmão fresco e saudável!\n\nLembre-se de que você pode personalizar o Poke Bowl adicionando ou substituindo ingredientes de acordo com suas preferências e dieta.",
}

export const chickenWrapRecipe = {
  title: "Wrap de Frango com Vegetais",
  content: "Para preparar o \"Wrap de Frango com Vegetais\", você precisará dos seguintes ingredientes:\n\n- 1 tortilla (pode ser de trigo, milho ou qualquer outra de sua preferência)\n- 100g de peito de frango cozido e desfiado\n- 1/4 de pimentão vermelho cortado em tiras\n- 1/4 de pimentão amarelo cortado em tiras\n- 1/4 de cebola roxa cortada em tiras\n- 1/2 cenoura ralada\n- 1/4 de abacate cortado em fatias\n- Alface ou rúcula a gosto\n- Temperos a gosto (como sal, pimenta-do-reino, suco de limão etc.)\n- Molho de sua preferência (como maionese, mostarda, molho de iogurte etc.)\n\nA preparação do \"Wrap de Frango com Vegetais\" é bastante simples. Siga os passos abaixo:\n\n1. Comece preparando todos os ingredientes, cortando-os e deixando-os prontos para montar o wrap.\n\n2. Aqueça a tortilla de acordo com as instruções da embalagem, para que ela fique macia e maleável.\n\n3. Espalhe o molho de sua preferência por toda a tortilla.\n\n4. Distribua o frango desfiado no centro da tortilla.\n\n5. Acrescente as tiras de pimentão, cebola, a cenoura ralada, as fatias de abacate e as folhas de alface ou rúcula.\n\n6. Tempere com os temperos de sua escolha, como sal, pimenta-do-reino e suco de limão.\n\n7. Dobre as laterais da tortilla para dentro, cobrindo levemente o recheio, e então enrole-a firmemente, formando um wrap.\n\n8. Se desejar, corte o wrap ao meio antes de servir.\n\nO \"Wrap de Frango com Vegetais\" pode ser servido imediatamente ou refrigerado por algumas horas antes de ser consumido. É uma opção prática e saudável para um lanche ou refeição rápida.",
}
